version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www/html
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        # Prevents container to start before other container, on which it depends
        depends_on:
            - php

    php:
        # Dockerfile path for customized image
        build: ./php
        working_dir: /var/www/html
        volumes:
            - ./www:/var/www/html
        networks:
            - code-network
        depends_on:
            - mysql

    mysql:    
        image: mysql:5.7  
        env_file:
        - ./www/.env
        volumes:
            # Volume for initial load in the database
            - ./data:/data
            # Volume for persistent MySQL data
            - ./data/db:/var/lib/mysql
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
